worker_processes auto;
error_log /dev/stderr notice;
pid /tmp/nginx.pid;

events {
    worker_connections 1024;
}

http {
    include /usr/local/openresty/nginx/conf/mime.types;
    default_type application/octet-stream;

    # Общие настройки логирования
    access_log /dev/stdout combined;
    error_log /dev/stderr;

    # Подключаем общие настройки Lua
    include /etc/nginx/conf.d/lua_settings.conf;

    # Подключаем конфигурацию rate limits
    include /etc/nginx/conf.d/rate_limits.conf;

    # Общие настройки upstream серверов
    include /etc/nginx/conf.d/upstreams.conf;

    server {
        listen 80;
        server_name localhost;

        # Common settings
        limit_conn per_ip_conn 20;

        # Подключаем общие locations
        include /etc/nginx/conf.d/locations/*.conf;

        # Health check endpoint
        location /health {
            access_log off;
            return 200 '{"status": "healthy"}';
        }
    }
}
