# JWT configuration
lua_shared_dict jwt_secrets 1m;
init_by_lua_block {
    jwt_secrets = ngx.shared.jwt_secrets
    local f = io.open("/etc/nginx/jwt_secret.key", "rb")
    local secret = f:read("*all")
    f:close()
    secret = string.gsub(secret, "^%s*(.-)%s*$", "%1")
    jwt_secrets:set("default", secret)
    ngx.log(ngx.NOTICE, "JWT secret key: '" .. secret .. "'")
}
