location /api/order-book/ {
    limit_req zone=private_api burst=100 nodelay;
    limit_req zone=per_ip burst=50;
    limit_req_status 429;
    error_page 429 = @too_many_requests;

    include /etc/nginx/conf.d/jwt_auth.conf;

    proxy_pass http://order-book-service/;
    include /etc/nginx/conf.d/proxy_settings.conf;
}
