# location /public/auth/ {
#     limit_req zone=public_api burst=20 nodelay;
#     limit_req zone=per_ip burst=50;
#     limit_req_status 429;
#     error_page 429 = @too_many_requests;

#     proxy_pass http://auth-service/;
#     include /etc/nginx/conf.d/proxy_settings.conf;
# }

# location /public/products/ {
#     limit_req zone=public_api burst=20 nodelay;
#     limit_req zone=per_ip burst=50;
#     limit_req_status 429;
#     error_page 429 = @too_many_requests;

#     proxy_pass http://products-service/;
#     include /etc/nginx/conf.d/proxy_settings.conf;
# }
